/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiStatusBanner: typeof import('./components/ApiStatusBanner.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ConsentBanner: typeof import('./components/ConsentBanner.vue')['default']
    DiaryEditor: typeof import('./components/DiaryEditor.vue')['default']
    DiaryEntryEditor: typeof import('./components/DiaryEntryEditor.vue')['default']
    JourneyView: typeof import('./components/JourneyView.vue')['default']
    LogoBrand: typeof import('./components/LogoBrand.vue')['default']
    MapView: typeof import('./components/MapView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
