# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  batch: true
  branches:
    include:
    - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageName: 'ccdiaryapi'
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'
  dotNetSolution: 'src/api/ccDiary.sln'
  containerRegistry: 'azure-container-registry'
  
stages:
- stage: Build
  jobs:
  - job: Build_UI
    steps:

    - task: PowerShell@2
      displayName: 'Set UI Version'
      inputs:
        targetType: inline
        script: |
          $NewContent = (Get-Content -Path src/UI/.env -Raw) -replace '(?<=VITE_BUILDNUMBER.*=.*")\d+(?=")', '$(Build.BuildId)'
          Set-Content -Path src/UI/.env -Value $NewContent

    - task: Npm@1
      displayName: "NPM Install"
      inputs:    
        command: 'install'
        workingDir: 'src/UI'

    - task: Npm@1
      displayName: "NPM Build"
      inputs:    
        command: 'custom'
        customCommand: 'run build'
        workingDir: 'src/UI'

    - task: ArchiveFiles@2
      displayName: Package UI
      inputs:
        rootFolderOrFile: 'src/UI/dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/uiPackage.zip'

    - publish: $(Build.ArtifactStagingDirectory)/uiPackage.zip
      displayName: Publish UI Package
      artifact: ui-package
  
  - job: Build_API
    steps:  
    - task: PowerShell@2
      displayName: 'Set API Version'
      inputs:
        targetType: inline
        script: |
          [Reflection.Assembly]::LoadWithPartialName("System.Xml.Linq")          
          $files = Get-ChildItem -Path src/api -Filter *.csproj -Recurse -ErrorAction SilentlyContinue -Force

          $files | foreach {
            $path = $_.fullname
            if (!$path.ToLower().Contains("test.csproj")) {
              $doc = [System.Xml.Linq.XDocument]::Load($path)
              $origVersion = $doc.Element("Project").Element("PropertyGroup").Element("AssemblyVersion").Value;
              $newVersion = "$($origVersion).$(Build.BuildId)"
              $doc.Element("Project").Element("PropertyGroup").Element("AssemblyVersion").SetValue($newVersion);
              $doc.Save($path)
              echo "Updated $($path) changing AssemblyVersion from '$($origVersion)' to '$($newVersion)'"
            }
            else {
              echo "Skipping $($path)"
            }
          }

    - task: Docker@2
      displayName: 'Build API Docker Image'
      inputs:    
        command: 'build'
        repository: '$(dockerImageName)'
        Dockerfile: 'src/api/ccDiaryApi/Dockerfile'
        buildContext: 'src/api'
        containerRegistry: $(containerRegistry)
        addPipelineData: true
        addBaseImageData: true
        tags: '$(tag)'

    - task: Docker@2
      displayName: 'Test API Docker Image'
      inputs:    
        command: 'build'
        repository: '$(dockerImageName)'
        Dockerfile: 'src/api/ccDiaryApi/Dockerfile'
        buildContext: 'src/api'
        containerRegistry: $(containerRegistry)
        addPipelineData: true
        addBaseImageData: true
        tags: '$(tag)'
        arguments: --target export-test-results --output type=local,dest=$(Build.ArtifactStagingDirectory)/testresults  

    - task: PublishTestResults@2
      displayName: Publish API Test Results
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: 'testresults.trx'
        searchFolder: '$(Build.ArtifactStagingDirectory)/testresults'
        testRunTitle: 'Publish Test Results *.trx'
        failTaskOnFailedTests: true
        failTaskOnMissingResultsFile: true
        failTaskOnFailureToPublishResults: true

    - task: PublishCodeCoverageResults@2
      displayName: Publish API Code Coverage
      inputs:
        pathToSources: '/'
        summaryFileLocation: '$(Build.ArtifactStagingDirectory)/testresults/coverage.*.xml'
        failIfCoverageEmpty : true

    - task: PowerShell@2 
      displayName: 'Save API Docker Image'
      inputs:
        targetType: inline        
        script: |
          docker image save $(containerRegistryLoginServer)/$(dockerImageName):$(tag) -o $(Build.ArtifactStagingDirectory)/$(dockerImageName).tar

    - publish:  $(Build.ArtifactStagingDirectory)/$(dockerImageName).tar
      displayName: Publish API Docker Image
      artifact: api-docker-image

- stage: Deploy
  jobs:
  - job: Deploy_UI_API
    steps:

    - checkout: none

    - download: current
      displayName: Extract UI Artifcats
      artifact: ui-package

    - download: current
      displayName: Extract API Artifcats
      artifact: api-docker-image

    - task: ExtractFiles@1
      displayName: Extract UI
      inputs:
        archiveFilePatterns: $(Pipeline.Workspace)/ui-package/uiPackage.zip
        destinationFolder: ui-extracted

    - task: AzureStaticWebApp@0
      displayName: Publish UI to Azure Static Web App
      inputs:
        app_location: ui-extracted
        skip_app_build: true
        skip_api_build: true    
        azure_static_web_apps_api_token: $(SiteDeploymentToken)

    - task: PowerShell@2 
      displayName: 'Load API Docker Image'
      inputs:
        targetType: inline
        script: |
          docker load --input $(Pipeline.Workspace)/api-docker-image/$(dockerImageName).tar
          docker tag $(containerRegistryLoginServer)/$(dockerImageName):$(tag)  $(containerRegistryLoginServer)/$(dockerImageName):latest

    - task: Docker@2
      displayName: 'Push API Docker Image to Azure Container Registry'
      inputs:    
        command: Push
        repository: '$(dockerImageName)'
        Dockerfile: 'src/api/ccDiaryApi/Dockerfile'
        buildContext: 'src/api'
        containerRegistry: $(containerRegistry)
        addPipelineData: true
        addBaseImageData: true
        tags: '$(tag),latest'

    - task: AzureContainerApps@1    
      displayName: 'Deploy to Azure Container App'
      inputs:
        azureSubscription: 'Cooking Code Subscription'
        containerAppName: $(containerAppName)
        resourceGroup: $(resourceGroup)
        imageToDeploy: '$(containerRegistryLoginServer)/$(dockerImageName):$(tag)'
