services:
  ccdiaryapi:
    environment:
      - DisableHttpsRedirection=true
      - RUN_MIGRATIONS=true
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    ports:
      - "54628:8080"
      - "54629:8080" # HTTPS is disabled, so we can use the same port for both HTTP and HTTPS
    volumes:
      - type: bind
        source: ${HTTPS_CERTS_PATH}
        target: /home/app/.aspnet/https
        read_only: true
