services:
  ccdiaryapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=443
      - RUN_MIGRATIONS=true
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/${HTTPS_CERT_FILE:-ccdiaryapi.pfx}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${HTTPS_CERT_PASSWORD}
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "54628:8080"
      - "54629:443"
    volumes:
      - type: bind
        source: ${USER_SECRETS_PATH}
        target: /home/app/.microsoft/usersecrets
        read_only: true